#!/bin/bash
# Installation script for Publisher Performance Portal
#
# This script sets up:
# 1. System user for running the service
# 2. PostgreSQL database
# 3. Application directory and permissions
# 4. Systemd service and timer
#
# Usage:
#   sudo ./install.sh
#
# Prerequisites:
#   - PostgreSQL installed and running
#   - Python 3.12+ installed
#   - Git installed

set -e

# Configuration
APP_USER="benchmark"
APP_GROUP="benchmark"
APP_DIR="/opt/integration-benchmarking"
DB_NAME="benchmark"
DB_USER="benchmark"

echo "=== Publisher Performance Portal Installation ==="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (sudo)"
    exit 1
fi

# Create system user if not exists
echo "Creating system user..."
if ! id "$APP_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /bin/false "$APP_USER"
    echo "  Created user: $APP_USER"
else
    echo "  User $APP_USER already exists"
fi

# Create application directory
echo "Setting up application directory..."
mkdir -p "$APP_DIR"
mkdir -p "$APP_DIR/logs"

# Copy application files (assuming we're in the source directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

if [ -d "$SOURCE_DIR" ] && [ -f "$SOURCE_DIR/publisher_benchmark.py" ]; then
    echo "  Copying application files from $SOURCE_DIR..."
    cp -r "$SOURCE_DIR"/* "$APP_DIR/"
else
    echo "  Warning: Source directory not found. Please copy files manually to $APP_DIR"
fi

# Set permissions
chown -R "$APP_USER:$APP_GROUP" "$APP_DIR"
chmod 750 "$APP_DIR"
chmod 770 "$APP_DIR/logs"

# Create virtual environment
echo "Creating Python virtual environment..."
if [ ! -d "$APP_DIR/venv" ]; then
    python3 -m venv "$APP_DIR/venv"
fi
"$APP_DIR/venv/bin/pip" install --upgrade pip
"$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt"
chown -R "$APP_USER:$APP_GROUP" "$APP_DIR/venv"

# Create PostgreSQL database
echo "Setting up PostgreSQL database..."
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    echo "  Database $DB_NAME already exists"
else
    sudo -u postgres createuser --no-superuser --no-createdb --no-createrole "$DB_USER" 2>/dev/null || true
    sudo -u postgres createdb --owner="$DB_USER" "$DB_NAME"
    echo "  Created database: $DB_NAME"
fi

# Generate random password for database user
DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24)
sudo -u postgres psql -c "ALTER USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"

# Create .env file
echo "Creating environment configuration..."
ENV_FILE="$APP_DIR/portal/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# Generated by install.sh on $(date)

# PostgreSQL
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME

# ClickHouse - Lazer cluster (fill in your values)
CLICKHOUSE_LAZER_HOST=your-lazer-host.clickhouse.cloud
CLICKHOUSE_LAZER_USER=your_user
CLICKHOUSE_LAZER_PASSWORD=your_password

# ClickHouse - Analytics cluster (fill in your values)
CLICKHOUSE_ANALYTICS_HOST=your-analytics-host.clickhouse.cloud
CLICKHOUSE_ANALYTICS_USER=your_user
CLICKHOUSE_ANALYTICS_PASSWORD=your_password

# API settings
API_HOST=0.0.0.0
API_PORT=8000
DEBUG=false

# Batch processing
BATCH_WORKERS=4
EOF
    chmod 600 "$ENV_FILE"
    chown "$APP_USER:$APP_GROUP" "$ENV_FILE"
    echo "  Created $ENV_FILE"
    echo "  IMPORTANT: Edit this file to add your ClickHouse credentials"
else
    echo "  Environment file already exists"
fi

# Run database migrations
echo "Running database migrations..."
cd "$APP_DIR"
sudo -u "$APP_USER" "$APP_DIR/venv/bin/alembic" -c portal/alembic.ini upgrade head

# Install systemd service and timer
echo "Installing systemd service..."
cp "$APP_DIR/portal/deploy/benchmark-daily.service" /etc/systemd/system/
cp "$APP_DIR/portal/deploy/benchmark-daily.timer" /etc/systemd/system/

systemctl daemon-reload
systemctl enable benchmark-daily.timer
systemctl start benchmark-daily.timer

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Next steps:"
echo "1. Edit $ENV_FILE to add your ClickHouse credentials"
echo "2. Test the batch job manually:"
echo "   sudo -u $APP_USER $APP_DIR/venv/bin/python -m portal.batch.daily_benchmark_runner --dry-run"
echo ""
echo "3. Check timer status:"
echo "   systemctl status benchmark-daily.timer"
echo ""
echo "4. View logs:"
echo "   journalctl -u benchmark-daily.service -f"
echo ""
echo "Database password saved to $ENV_FILE"
